mongo-url = "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/movie?replicaSet=rp0"

elasticsearch-urls = ["http://elasticsearch:9200"]

elasticsearch-max-conns = 4

elasticsearch-max-seconds = 5

elasticsearch-max-bytes = 8000000

dropped-collections = false

dropped-databases = false

namespace-regex = "^movie.sudar"
direct-read-namespaces = ["movie.sudar.movie","movie.sudar.history"]

[[mapping]]
namespace = "movie.sudar.movie"
index = "movie"

[[mapping]]
namespace = "movie.sudar.history"
index = "history"



[[script]]
namespace = "movie.sudar.movie"
script = """
module.exports = function(doc) {
  var newdoc = {
     name : doc.name,
     director : doc.director,
     actors : doc.actors,
  }
  return newdoc;
}
"""